---
abstract: 'Block CSRF Attacks with minimal changes to your app'
author:
  - 'Rintaro Ishizaki <rintaro@cpan.org>'
  - 'William Wolf <throughnothing@gmail.com>'
  - 'Matthew Phillips <mattp@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Session::State::Cookie: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-CSRFBlock
requires:
  Digest::SHA1: 0
  HTML::Parser: 0
  Plack::Middleware: 0
  Plack::Request: 0
  Plack::TempBuffer: 0
  Plack::Util: 0
  Plack::Util::Accessor: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/mattp-/Plack-Middleware-CSRFBlock.git
version: 0.08
