---
abstract: 'Block CSRF Attacks with minimal changes to your app'
author:
  - 'Rintaro Ishizaki <rintaro@cpan.org>'
  - 'William Wolf <throughnothing@gmail.com>'
  - 'Matthew Phillips <mattp@cpan.org>'
build_requires:
  File::Spec: 0
  HTTP::Request::Common: 0
  IO::Handle: 0
  IPC::Open3: 0
  Plack::Middleware::Session: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-CSRFBlock
requires:
  Digest::SHA1: 0
  HTML::Parser: 0
  Plack: 0
  Time::HiRes: 0
resources:
  repository: git://github.com/mattp-/Plack-Middleware-CSRFBlock.git
version: 0.09
